version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-mc:/var/lib/postgresql/data:delegated
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always


volumes:
  postgres-data:
